name: Build and deploy ClickCart Backend

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22.x"

      - name: Install backend dependencies
        working-directory: backend
        run: npm install

      - name: Build and test backend
        working-directory: backend
        run: |
          npm run build --if-present
          npm run test --if-present

      - name: Upload backend
        uses: actions/upload-artifact@v4
        with:
          name: clickcart-backend
          path: backend

  deploy:
    runs-on: ubuntu-latest
    needs: build

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download backend
        uses: actions/download-artifact@v4
        with:
          name: clickcart-backend
          path: backend

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_9F5ECDC9E79946FE86E70F85DF09EF51 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_69374163FB934159B8008598DFB3C4BD }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_74567BA290764E5FB1C9DB1B2EF49E00 }}

      - name: Configure App Settings
        uses: azure/appservice-settings@v1
        with:
          app-name: "clickcart"
          app-settings-json: |
            [
              {
                "name": "MONGO_URL",
                "value": "${{ secrets.MONGO_URL }}",
                "slotSetting": false
              },
              {
                "name": "JWT_SECRET",
                "value": "${{ secrets.JWT_SECRET }}",
                "slotSetting": false
              }
            ]

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: "clickcart"
          slot-name: "Production"
          package: ./backend
